// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_Q1bsdvk0FDV1P82doFommI-9qCmIVw',
    appId: '1:712922289189:web:69fc8c08d67bcbe847dbcc',
    messagingSenderId: '712922289189',
    projectId: 'pesquisasatisfacao-20d26',
    authDomain: 'pesquisasatisfacao-20d26.firebaseapp.com',
    storageBucket: 'pesquisasatisfacao-20d26.firebasestorage.app',
    measurementId: 'G-G7E58VF66Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXue3hEiI9h3gmiBcDBYqOpkWvqXmGcQ',
    appId: '1:712922289189:android:3f19615781fda8a447dbcc',
    messagingSenderId: '712922289189',
    projectId: 'pesquisasatisfacao-20d26',
    storageBucket: 'pesquisasatisfacao-20d26.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC_Q1bsdvk0FDV1P82doFommI-9qCmIVw',
    appId: '1:712922289189:web:fd2ed30a234a857847dbcc',
    messagingSenderId: '712922289189',
    projectId: 'pesquisasatisfacao-20d26',
    authDomain: 'pesquisasatisfacao-20d26.firebaseapp.com',
    storageBucket: 'pesquisasatisfacao-20d26.firebasestorage.app',
    measurementId: 'G-8SDWW8ERTR',
  );

}